p2g33_web/Models/Domain/Element.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace p2g33_web.Models.Domain
{
    public abstract class Element
    {
        [Key]
        [Required]
        public int elementId { get; set; }
        public DateTime? availableFrom { get; set; }
        public DateTime? availableUntil { get; set; }
        [DisplayName("Omschrijving")]
        public string description { get; set; }
        public string keyWords { get; set; }
        public string targetGroup { get; set; }
        public string title { get; set; }
    }
}

p2g33_web/Models/ViewModels/EndOfStatementGameViewModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using p2g33_web.Models.Domain;

namespace p2g33_web.Models.ViewModels
{
    public class EndOfStatementGameViewModel
    {
        public EndOfStatementGameViewModel(){}

        public EndOfStatementGameViewModel(VKUser user,LearningProcess learningProcess,StatementGame statementGame)
        {
            Title = statementGame.title;
            Questions = new List<string>();
            foreach (var q in user.GetUserAnswers<StatementGameUserAnswer>())
            {
                Questions.Add(q.StatementGameQuestion.question);
            }
            Answers = new List<string>();
            foreach (var a in user.GetUserAnswers<StatementGameUserAnswer>())
            {
                Answers.Add(a.StatementGameAnswer.answer);
            }
            LearningProcessCode = learningProcess.learningProcessCode;
        }

        public string Title { get; set; }
        public IList<string> Questions { get; set; }
        public IList<string> Answers { get; set; }
        public string LearningProcessCode { get; set; }
    }
}

p2g33_web/Controllers/ElementController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using p2g33_web.Models.Domain;
using p2g33_web.Models.ViewModels;

namespace p2g33_web.Controllers
{
    [Authorize]
    public class ElementController : Controller
    {
        private IVKUserRepository UserRepository;
        private Element _element;

        public ElementController(IVKUserRepository userRepository)
        {
            this.UserRepository = userRepository;
        }

        public ActionResult PlayStatementGame(DetailsStatementGameViewModel model, VKUser user)
        {
            var learningProcess = user.GetLearningProcess(model.LearningProcessCode);
            var statementGame = learningProcess.GetElementByType<StatementGame>(model.ElementId);

            Session["QuestionIndex"] = 0;

            if (user.internalUser)
                TempData["Info"] = "Uw resultaten worden niet opgeslagen, omdat u een interne medewerker bent!";
            if (user.CheckPlayed(model.ElementId, learningProcess.learningProcessCode))
                TempData["Info"] = "U heeft dit stellingenspel reeds gespeeld, uw antwoorden worden dit keer niet meer opgeslagen";

            return View(new StatementGameViewModel(statementGame,learningProcess));
        }

        [HttpPost]
        public ActionResult SaveStatementGame(StatementGameViewModel model, VKUser user)
        {
            var learningProcess = user.GetLearningProcess(model.LearningProcessCode);
            var statementGame = learningProcess.GetElementByType<StatementGame>(model.ElementId);
            var questionIndex = (int)Session["QuestionIndex"];

            if (model.AnswerId != 0)
            {

                if (!user.internalUser)
                {
                    if (user.CheckPlayed(model.ElementId, model.LearningProcessCode) == false)
                        UserRepository.AnswerStatementGameQuestion(user, model.LearningProcessCode, model.AnswerId,
                            statementGame.StatementGameQuestions[questionIndex].statementGameQuestionId, model.ElementId);
                }

                var nextQuestionIndex = (int) Session["QuestionIndex"] + 1;
                if (nextQuestionIndex >= statementGame.StatementGameQuestions.Count)
                {
                    TempData["Succes"] = "Stellingenspel werd succesvol afgerond!";
                    if (user.internalUser)
                    {
                        return RedirectToAction("DetailsLearningProcess", "LearningProcesses",
                                                new {id = learningProcess.learningProcessCode});
                    }
                    return View("EndOfStatementGame", new EndOfStatementGameViewModel(user, learningProcess,statementGame));
                }

                model.StatementGameQuestion =
                    new StatementGameQuestionViewModel(statementGame.StatementGameQuestions[nextQuestionIndex]);
                model.AnswerId = 1;
                Session["QuestionIndex"] = nextQuestionIndex;
                return View("PlayStatementGame", model);
            }
            model.StatementGameQuestion = new StatementGameQuestionViewModel(statementGame.StatementGameQuestions[questionIndex]);
            return View("PlayStatementGame",model);
        }

        [HttpPost]
        public ActionResult PlayCase(DetailsCaseViewModel model,VKUser user)
        {
            var learningProcess = user.GetLearningProcess(model.LearningProcessCode);
            var thiscase = learningProcess.GetElementByType<Case>(model.ElementId);

            if (user.internalUser)
                TempData["Info"] = "Uw resultaten worden niet opgeslagen, omdat u een interne medewerker bent!";
            if (user.CheckPlayed(model.ElementId, model.LearningProcessCode))
                TempData["Info"] = "U heeft deze casus reeds gespeeld, uw antwoorden worden dit keer niet meer opgeslagen";
            
            return View(new CaseViewModel(thiscase, learningProcess));
        }

        [HttpPost]
        public ActionResult SaveFirstCase(CaseViewModel model, VKUser user)
        {
            var learningProcess = user.GetLearningProcess(model.LearningProcessCode);
            var acase = learningProcess.GetElementByType<Case>(model.ElementId);

            if (model.AnswerId != 0)
            {
                model.Question = new CaseQuestionViewModel(acase.caseQuestion);
                var answer = acase.caseQuestion.getAnswerById(model.AnswerId);
                if (answer != null)
                {
                    Session["QuestionId"] = acase.caseQuestion.caseQuestionId;
                    if (HttpContext.Request.IsAjaxRequest())
                    {
                        if (!user.internalUser)
                        {
                            if (user.CheckPlayed(model.ElementId, model.LearningProcessCode) == false)
                                UserRepository.AnswerCaseQuestion(user, model.LearningProcessCode, model.AnswerId,
                                                                  acase.caseQuestion.caseQuestionId, model.ElementId);
                        }
                        model.Feedback = answer.feedback;
                        if (model.Feedback != null)
                            return PartialView("FeedbackCase", model);
                        model.Feedback = "Voor deze vraag is er geen feedback";
                        return PartialView("FeedbackCase", model);
                    }
                }
                else
                {
                    return View("Error");
                }
            }
            model.Question = new CaseQuestionViewModel(acase.caseQuestion);
            return View("PlayCase", model);
        }

        [HttpPost]
        public ActionResult PlayRestCase(CaseViewModel model, VKUser user)
        {
            var learningProcess = user.GetLearningProcess(model.LearningProcessCode);
            var acase = learningProcess.GetElementByType<Case>(model.ElementId);

            if (model.AnswerId != 0)
            {
                var question = acase.GetQuestion((int) Session["QuestionId"]);
                var answer = question.getAnswerById(model.AnswerId);
                if (HttpContext.Request.IsAjaxRequest())
                {
                    model.Question = new CaseQuestionViewModel(question);
                    model.Feedback = answer.feedback;
                    if(model.Feedback!=null)
                        return PartialView("FeedbackRestCase", model);
                    model.Feedback = "Voor deze vraag is er geen feedback";
                    return PartialView("FeedbackRestCase", model);
                }
                if (answer.nextQuestion != null)
                {
                    var nextQuestion = answer.nextQuestion;
                    model.Question = new CaseQuestionViewModel(nextQuestion);
                    Session["QuestionId"] = model.Question.QuestionId;
                    return View("PlayRestCase", model);
                }
                return View("EndOfCase",model);
            }
            var q = acase.GetQuestion((int) Session["QuestionId"]);
            model.Question = new CaseQuestionViewModel(q);
            return View("PlayRestCase", model);
        }

        [HttpPost]
        public ActionResult PlayBox(DetailsBoxViewModel model, VKUser user)
        {
            var learningProcess = user.GetLearningProcess(model.LearningProcessCode);
            var box = learningProcess.GetElementByType<Box>(model.ElementId);
            var boxmodel = new BoxViewModel(box, learningProcess);
            Session["ImageUrlsRemaining"] = boxmodel.ImageUrlsRemaining;
            Session["ImageUrlsChosen"] = boxmodel.ImageUrlsChosen;
            if (user.CheckPlayed(model.ElementId, model.LearningProcessCode))
            {
                TempData["Info"] =
                    "U heeft dit spel al gespeeld. De antwoorden die u nu geeft zullen de vorige antwoorden overschrijven.";
            }
            if (user.internalUser)
            {
                TempData["Info"] = "Uw resultaten worden niet opgeslagen, omdat u een interne medewerker bent!";
            }
            return View(boxmodel);
        }

        [HttpPost]
        public ActionResult SaveBoxQuestion(BoxViewModel model, VKUser user)
        {
            var learningProcess = user.GetLearningProcess(model.LearningProcessCode);
            var box = learningProcess.GetElementByType<Box>(model.ElementId);
            model.ImageUrlsRemaining = (List<String>)Session["ImageUrlsRemaining"];
            model.ImageUrlsChosen = (List<String>) Session["ImageUrlsChosen"];
            if (model.Motivation !=null && model.ChosenImageUrl !=null)
            {
                model.ImageUrlsChosen.Add(model.ChosenImageUrl);
                model.ImageUrlsRemaining.Remove(model.ChosenImageUrl);
                Session["ImageUrlsRemaining"] = model.ImageUrlsRemaining;
                Session["ImageUrlsChosen"] = model.ImageUrlsChosen;

                if (!user.internalUser)
                {
                    UserRepository.AnswerBoxQuestion(user, model.LearningProcessCode, model.ChosenImageUrl,
                                                     box.questions[model.CurrentQuestionIndex].boxQuestionId,
                                                     box.elementId, model.Motivation);

                }
                model.CurrentQuestionIndex++;
                if (box.questions.Count <= model.CurrentQuestionIndex || model.ImageUrlsRemaining == null)
                {
                    TempData["Succes"] = "Doos werd succesvol afgerond!";
                    return View("EndBox", new EndOfBoxViewModel(user, learningProcess, box));
                }
                model.Question = box.questions[model.CurrentQuestionIndex].question;
                model.Motivation = null;
                ModelState.Clear();

p2g33_web/Views/Element/EndBox.cshtml
@model p2g33_web.Models.ViewModels.EndOfBoxViewModel

@{
    ViewBag.Title = "Overzicht doos";
}

<h2>Overzicht doos: @Html.DisplayFor(t => t.Title)</h2>
<legend>@Html.DisplayFor(t => t.Description)</legend>
<div>
    @for (var i=0; i < Model.Questions.Count; i ++ )
    {
        <div class="well well-small">
            <table class="table">                    
                <tr>
                    <td>
                        <p>
                            <strong>Gekozen afbeelding:</strong>
                        </p>
                        <img src="@Model.Images[i]" alt="imageBox" class="img-rounded" style="max-height: 200px;max-width: 300px"/> 
                    </td> 
                    <td>
                        <strong>Vraag: </strong>@Html.DisplayFor(t => t.Questions[i])<br/>
                        <strong>Motivatie: </strong>
                        @Html.DisplayFor(t => t.Answers[i])<br/>
                    </td>    
                </tr> 
            </table>
        </div>
            
    }


    @Html.ActionLink("Terug naar details van leertraject", "DetailsLearningProcess", "LearningProcesses", new { id = Model.LearningProcessCode },null)
    
</div>

p2g33_web/Views/Element/EndOfCase.cshtml
@model p2g33_web.Models.ViewModels.CaseViewModel
@{
    ViewBag.Title = Model.Title;
}

<h2>@ViewBag.Title</h2>
<div>
    @if (Model.Feedback != null)
     {
         <h4>Feedback vorige vraag:</h4>
         <p>@Model.Feedback</p>
    }

    <div class="alert alert-success">
        De casus werd succesvol afgerond!
    </div>

    <p>
        @Html.ActionLink("Terug naar details van leertraject", "DetailsLearningProcess", "LearningProcesses", new { id = Model.LearningProcessCode },null)
    </p>
</div>

p2g33_web/Views/Element/EndOfStatementGame.cshtml
@model p2g33_web.Models.ViewModels.EndOfStatementGameViewModel
@{
    ViewBag.Title = Model.Title;
}

<h2>@ViewBag.Title</h2>
<div>
    <h3>Dit waren uw antwoorden:</h3>
    @for (int i = 0; i < Model.Questions.Count; i++)
    {
        <div class="well well-small">
            <strong>Vraag: </strong>@Html.DisplayFor(t => t.Questions[i])<br/>
            <strong>Antwoord: </strong>
            @if (Model.Answers[i].Equals("rood"))
            {
                <div>Dit is ernstig. Hier moet klacht worden neergelegd zodat justitie zijn werk kan doen.</div>
            }
            else if(Model.Answers[i].Equals("geel"))
            {
                <div>Dit gaat te ver. Ingrijpen is noodzakelijk en hulpverlening moet een kans krijgen. Als het niet vrijwillig kan moet er een andere weg gezocht worden.</div>
            } 
            else if (Model.Answers[i].Equals("groen"))
            {
                <div>Er is iets aan de hand, maar dat moet niet worden overdreven. De persoon moet wel gewezen worden op zijn problematisch gedrag en hulpverlening moet aangeraden worden.</div>
            } 
            else if (Model.Answers[i].Equals("blauw"))
            {
                <div>We leven in een tolerante maatschappij. Hier is niets problematisch aan de hand. Dit moet kunnen.</div>
            }
            else
            {
                @Html.DisplayFor(t => t.Answers[i])
            }
        </div>
    }
    <p>
        @Html.ActionLink("Terug naar details van leertraject", "DetailsLearningProcess", "LearningProcesses", new { id = Model.LearningProcessCode },null)
    </p>
</div>

p2g33_web/Views/Element/FeedbackCase.cshtml
@model p2g33_web.Models.ViewModels.CaseViewModel

@{
    AjaxOptions ajaxOpts = new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        Url = Url.Action("SaveFirstCase", "Element"),
        UpdateTargetId = "body-case"
    };
}

@if (Model.Feedback != null)
{
    <div class="well">
        
        <h4>@Model.Question.Question</h4>
        @if (Model.Question.Consideration != null)
        {
            <p>
                <strong>Bedenking: </strong>@Model.Question.Consideration
            </p>
        }
        @foreach (var answer in Model.Question.Answers)
        {
            <p>@Html.RadioButtonFor(t => t.AnswerId, answer.AnswerId,new {disabled = "disabled"}) @answer.Answer</p>
        }   
            
    </div>
    using (Html.BeginForm("PlayRestCase", "Element", FormMethod.Post))
    {
        @Html.HiddenFor(t => t.LearningProcessCode)
        @Html.HiddenFor(t => t.Title)
        @Html.HiddenFor(t => t.Description)
        @Html.HiddenFor(t => t.Question)
        @Html.HiddenFor(t => t.ElementId)
        @Html.HiddenFor(t => t.AnswerId)
        <div class="well">
            <h4>Feedback:</h4>
            <p>@Model.Feedback</p>
            <input type="submit" class="btn btn-primary" value="Verder"/>
        </div>
    }
    
}
else
{
    <div class="well">
        @using (Ajax.BeginForm("SaveFirstCase", ajaxOpts))
        {
            @Html.HiddenFor(t => t.LearningProcessCode)
            @Html.HiddenFor(t => t.Title)
            @Html.HiddenFor(t => t.Description)
            @Html.HiddenFor(t => t.ElementId)

            <h4>@Model.Question.Question</h4>
            if (Model.Question.Consideration != null)
            {
                <p>
                    <strong>Bedenking: </strong>@Model.Question.Consideration
                </p>
            }
            foreach (var answer in Model.Question.Answers)
            {
                <p>@Html.RadioButtonFor(t => t.AnswerId, answer.AnswerId) @answer.Answer</p>
            }

            <input type="submit" class="btn btn-primary" value="Verder"/>
            <span class="help-inline">
                @Html.ValidationMessageFor(m => m.AnswerId)
            </span>
        }  
        </div>
}

p2g33_web/Views/Element/FeedbackRestCase.cshtml
@model p2g33_web.Models.ViewModels.CaseViewModel

@{
    AjaxOptions ajaxOpts = new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        Url = Url.Action("PlayRestCase", "Element"),
        UpdateTargetId = "body-case"
    };
}

@if (Model.Feedback != null)
{
    <div class="well">
        
        <h4>@Model.Question.Question</h4>
        @if (Model.Question.Consideration != null)
        {
            <p>
                <strong>Bedenking: </strong>@Model.Question.Consideration
            </p>
        }
        @foreach (var answer in Model.Question.Answers)
        {
            <p>@Html.RadioButtonFor(t => t.AnswerId, answer.AnswerId,new {disabled = "disabled"}) @answer.Answer</p>
        }   
            
    </div>
    using (Html.BeginForm("PlayRestCase", "Element", FormMethod.Post))
    {
        @Html.HiddenFor(t => t.LearningProcessCode)
        @Html.HiddenFor(t => t.Title)
        @Html.HiddenFor(t => t.Description)
        @Html.HiddenFor(t => t.Question)
        @Html.HiddenFor(t => t.ElementId)
        @Html.HiddenFor(t => t.AnswerId)
        <div class="well">
            <h4>Feedback:</h4>
            <p>@Model.Feedback</p>
            <input type="submit" class="btn btn-primary" value="Verder"/>
        </div>
    }
    
}
else
{
    <div class="well">
        @using (Ajax.BeginForm("PlayRestCase", ajaxOpts))
        {
            @Html.HiddenFor(t => t.LearningProcessCode)
            @Html.HiddenFor(t => t.Title)
            @Html.HiddenFor(t => t.Description)
            @Html.HiddenFor(t => t.ElementId)

            <h4>@Model.Question.Question</h4>
            if (Model.Question.Consideration != null)
            {
                <p>
                    <strong>Bedenking: </strong>@Model.Question.Consideration
                </p>
            }
            foreach (var answer in Model.Question.Answers)
            {
                <p>@Html.RadioButtonFor(t => t.AnswerId, answer.AnswerId) @answer.Answer</p>
            }

            <input type="submit" class="btn btn-primary" value="Verder"/>
            <span class="help-inline">
                @Html.ValidationMessageFor(m => m.AnswerId)
            </span>
        }  
        </div>
}

p2g33_web/Views/Element/PlayBox.cshtml
@model p2g33_web.Models.ViewModels.BoxViewModel

@{
    ViewBag.Title = Model.Title;
}

<h2>@Html.DisplayFor(t => t.Title)</h2>
<legend>@Html.DisplayFor(t => t.Description)</legend>
<div class="well">
    @using (Html.BeginForm("SaveBoxQuestion", "Element", FormMethod.Post))
    {
        @Html.HiddenFor(t=>t.Title)
        @Html.HiddenFor(t=>t.Description)
        @Html.HiddenFor(t=>t.LearningProcessCode)
        @Html.HiddenFor(t=>t.ElementId)
        @Html.HiddenFor(t => t.NumberOfQuestions)
        @Html.HiddenFor(t => t.CurrentQuestionIndex)
        @Html.HiddenFor(t => t.ImageUrlsChosen)
        @Html.HiddenFor(t => t.ImageUrlsRemaining)

        @Html.ValidationSummary()
        <h4>
            @Html.DisplayFor(t => t.Question)
        </h4>
        <h4>Selecteer een afbeelding:</h4>
        <table class="table table-striped table-bordered">
          
            @foreach (var img in Model.ImageUrlsRemaining)
            {
                <tr>
                    <td style="text-align: center">
                        @Html.RadioButtonFor(t => Model.ChosenImageUrl, img)
                    </td>
                    <td>
                        <img src="@img" alt="imageBox" class="img-rounded" style="max-height: 200px;max-width: 300px"/>
                    </td> 
                </tr>
            }
           
        </table>
            <h4>Motivatie voor de gekozen afbeelding:</h4>
            @Html.TextAreaFor(t => t.Motivation)
        
        <input type="submit" class="btn btn-primary" value="Verder"/>
      
    }
</div>

 @{
        var vraag = Model.CurrentQuestionIndex + 1;
        var width = (vraag*100)/Model.NumberOfQuestions; 
    }   

    <div class="progress progress-striped active">
        @* ReSharper disable UnexpectedValue *@
        <div class="bar" style="width: @width%;"></div>
    </div>


@Scripts.Render("~/bundles/jqueryval")

p2g33_web/Views/Element/PlayCase.cshtml
@model p2g33_web.Models.ViewModels.CaseViewModel

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/jquery-1.6.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
}

@{
    ViewBag.Title = Model.Title;
}

<h2>@Html.DisplayFor(t => t.Title)</h2>
<legend>@Html.DisplayFor(t => t.Description)</legend>
<div id="body-case">
    @Html.Partial("FeedbackCase",Model)
</div>

p2g33_web/Views/Element/PlayRestCase.cshtml
@model p2g33_web.Models.ViewModels.CaseViewModel

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/jquery-1.6.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
}

@{
    ViewBag.Title = Model.Title;
    AjaxOptions ajaxOpts = new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        Url = Url.Action("PlayRestCase","Element"),
        UpdateTargetId = "body-case"
    };
}

<h2>@Html.DisplayFor(t => t.Title)</h2>
<legend>@Html.DisplayFor(t => t.Description)</legend>

<div id="body-case">
    @Html.Partial("FeedbackRestCase",Model)
</div>

    

p2g33_web/Views/Element/PlayStatementGame.cshtml
@using p2g33_web.Models.ViewModels
@model p2g33_web.Models.ViewModels.StatementGameViewModel

@{
    ViewBag.Title = Model.Title;
}

<h2>@Html.DisplayFor(t => t.Title)</h2>
<legend>@Html.DisplayFor(t => t.Description)</legend>
<div class="well">
    @using (Html.BeginForm("SaveStatementGame", "Element", FormMethod.Post))
    {
        @Html.HiddenFor(t => t.LearningProcessCode)
        @Html.HiddenFor(t => t.ElementId)
        @Html.HiddenFor(t => t.Title)
        @Html.HiddenFor(t => t.Description)
        @Html.HiddenFor(t => t.NumberOfQuestions)
        
        <h4>@Model.StatementGameQuestion.Question</h4>
        foreach (var answer in Model.StatementGameQuestion.Answers)
        {
            if (answer.Answer.Equals("rood"))
            {
                <p>@Html.RadioButtonFor(t => t.AnswerId, answer.AnswerId) Dit is ernstig. Hier moet klacht worden neergelegd zodat justitie zijn werk kan doen.</p>
            }
            else if(answer.Answer.Equals("geel"))
            {
                <p>@Html.RadioButtonFor(t => t.AnswerId, answer.AnswerId) Dit gaat te ver. Ingrijpen is noodzakelijk en hulpverlening moet een kans krijgen. Als het niet vrijwillig kan moet er een andere weg gezocht worden.</p>
            } 
            else if (answer.Answer.Equals("groen"))
            {
                <p>@Html.RadioButtonFor(t => t.AnswerId, answer.AnswerId) Er is iets aan de hand, maar dat moet niet worden overdreven. De persoon moet wel gewezen worden op zijn problematisch gedrag en hulpverlening moet aangeraden worden.</p>
            } 
            else if (answer.Answer.Equals("blauw"))
            {
                <p>@Html.RadioButtonFor(t => t.AnswerId, answer.AnswerId) We leven in een tolerante maatschappij. Hier is niets problematisch aan de hand. Dit moet kunnen.</p>
            }
            else
            {
                <p>@Html.RadioButtonFor(t => t.AnswerId, answer.AnswerId) @answer.Answer</p>
            }
        }
        <br/>
        <input type="submit" class="btn btn-primary" value="Verder"/> 
        <span class="help-inline">
            @Html.ValidationMessageFor(m => m.AnswerId)
        </span>
    }
</div>
    @{
        var vraag = (int) Session["questionIndex"]+1;
        var width = (vraag*100)/Model.NumberOfQuestions; 
    }   

    <div class="progress progress-striped active">
        @* ReSharper disable UnexpectedValue *@
        <div class="bar" style="width: @width%;"></div>
    </div>


@Scripts.Render("~/bundles/jqueryval")

p2g33_web/Views/Element/ViewDocument.cshtml
@model p2g33_web.Models.ViewModels.DocumentViewModel 

@{
    ViewBag.Title = @Model.Title;
}

<h2>@ViewBag.Title</h2>

<div>
    <p>
        @Html.ActionLink("Terug naar details van leertraject", "DetailsLearningProcess", "LearningProcesses", new { id = Model.LearningProcessCode },null)
    </p>
</div>

@if (Session["format"].Equals("pdf"))
{
    <div class="text-center">
        <iframe width="100%" height="600px" src="@Model.FileLocation?mode=mobile" frameborder="0" allowfullscreen="false" />
    </div>
}

@if (Session["format"].Equals("video"))
{
    <div class="text-center">
        <video width="320" height="240" controls="true">
            <source src="@Model.FileLocation">
            Video niet ondersteund door browser.
        </video>
    </div>
}

@if (Session["format"].Equals("other")) {
<div>
    <p>
        <a href="@Model.FileLocation">Download @Model.Title</a>
    </p>
</div>
}